name: pushandgrasp
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - attrs=19.3.0
  - backcall=0.2.0
  - bleach=3.1.5
  - ca-certificates
  - certifi=2020.6.20
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - ipykernel=5.3.0
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - jedi=0.17.1
  - jinja2=2.11.2
  - jsonschema=3.2.0
  - jupyter_client=6.1.3
  - jupyter_core=4.6.3
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - markupsafe=1.1.1
  - mistune=0.8.4
  - nbconvert=5.6.1
  - nbformat=5.0.7
  - ncurses=6.2
  - notebook=6.0.3
  - openssl=1.1.1g
  - packaging=20.4
  - pandoc=2.9.2.1
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.1.1
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.5
  - ptyprocess=0.6.0
  - pygments=2.6.1
  - pyparsing=2.4.7
  - pyrsistent=0.16.0
  - python=3.7
  - python-dateutil=2.8.1
  - pyzmq=19.0.1
  - readline=8.0
  - send2trash=1.5.0
  - setuptools=47.3.1
  - six=1.15.0
  - sqlite=3.32.3
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.10
  - tornado=6.0.4
  - traitlets=4.3.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.34.2
  - xz=5.2.5
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - pip:
    - addict==2.4.0
    - catkin-pkg==0.4.23
    - cloudpickle==1.3.0
    - cycler==0.10.0
    - cython==0.29.20
    - distro==1.5.0
    - docutils==0.16
    - future==0.18.2
    - gym==0.17.2
    - ipywidgets==7.5.1
    - joblib==1.0.0
    - kiwisolver==1.2.0
    - matplotlib==3.2.2
    - numpy==1.19.0
    - open3d==0.11.2
    - opencv-python==4.2.0.34
    - pandas==1.1.5
    - pillow==7.2.0
    - plyfile==0.7.2
    - pybullet==3.0.7
    - pycocotools==2.0.1
    - pyglet==1.5.0
    - pytz==2020.4
    - pyyaml==5.3.1
    - rospkg==1.2.9
    - scikit-learn==0.23.2
    - scipy==1.5.0
    - sklearn==0.0
    - threadpoolctl==2.1.0
    - torch==1.2.0
    - torchvision==0.4.0
    - tqdm==4.54.1
    - widgetsnbextension==3.5.1


