model:
  path: /home/baris/Workspace/push-to-see/saved_models/mask_rg
  # set  'file:' to 'new' for training from scratch, 'pretrained' for transfer learning,
  # or the name of the save model file which is placed on the above path folder.
  file: my_model_inria_v1_20ep-40ep__epoch_no_19_2020-09-04.00:12:07.pth #new

  settings:
    epochs: 20
    learning_rate: 0.0001
    batch_size: 5
    backbone: resnet50
    backbone_pretrained: True
    cuda_available: True


dataset:
  path: /home/baris/Database # The folders and files in the subsections below should be placed in this folder.
  images: depth_ims/NUMPY
  masks: segmentation_masks/PNG
  train_indices: train_indices.npy
  test_indices: test_indices.npy
  is_depth: True   # if this flag is set 'True', trainer will look for depth numpy arrays in 'images' folder
  data_augmentation: False

saving:
  path: saved_models/inria_train_2
  model_name: my_model_inria_v2_0ep_
  config_name:
